# Generated by Django 5.2.9 on 2026-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_student_user_alter_user_role_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
