# Generated by Django 5.2.9 on 2026-02-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_collegeevent_collegephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
