# Generated by Django 5.2.9 on 2026-02-24 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0005_user_is_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_app.faculty'),
        ),
    ]
