# Generated by Django 5.2.9 on 2026-02-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0006_marks_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Campus Update', max_length=200),
        ),
    ]
