# Generated by Django 5.2.9 on 2026-02-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0007_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], default='Morning', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'session')},
        ),
    ]
